owner: jhonsrodrigues
repo: status.xyztools.app
sites:
  - name: XYZTools
    url: https://xyztools.app/

assignees:
  - jhonsrodrigues

status-website:
  theme: light
  cname: status.xyztools.app

secrets:
  - NOTIFICATION_DISCORD
  - NOTIFICATION_DISCORD_WEBHOOK_URL
