owner: jhonsrodrigues
repo: status.xyztools.app
sites:
  - name: XYZTools
    url: https://xyztools.app/

assignees:
  - seu-usuario-do-github

status-website:
  theme: light
  # baseUrl: /xyztools-status # Descomente essa linha se a página ficar no domínio padrão do github.io

secrets:
  - NOTIFICATION_DISCORD
  - NOTIFICATION_DISCORD_WEBHOOK_URL
